### ISSUE TITLE
invalid device function

### ISSUE THREAD

**Issue by Sarah20187** [cfzd/MTA_lane_detection#1]
Thank you for your pytorch implementation.
I can directly import PSA module after downloading. But I have the "invalid device function" all the time when I began training. Could you help me with that?

**Comment by cfzd** [comment]
Sorry, this is a temporary version of our implementation of PyTorch  PSANet for my previous work. So we haven't added the corresponding instructions. If you want to use this code, you should run
`sh ./make.sh`
in the first step. This will bulid the CUDA code of PSANet and then you can import it anywhere you like. 

After all, this is a temporary version, so it could only run in a CUDA device and has a little problem of memeory leakage(could train ~10k images for 11G cuda mem). We have fixed the problem, but I'm currently occupied in finishing my paper response. We will realease the updated version soon.
